#!/usr/bin/env bash
# refresh_indexes.sh — rebuild the 4 index pairs idempotently
#
# Indexes rebuilt:
#   1. docs/project/sprints/INDEX.md          (from sprint-S*.md files)
#   2. docs/project/sprints/sprint-S<N>-index.md  (per active sprint)
#   3. docs/project/backlog-index.md          (from backlog.md sprint sections)
#   4. docs/designs/sprint-S<N>/INDEX.md   (per sprint design dir)
#
# Usage: refresh_indexes.sh [REPO_ROOT]
#   REPO_ROOT defaults to $(git rev-parse --show-toplevel) or PWD.
#
# Exit codes:
#   0 — success (one or more indexes rebuilt, including 0-row indexes)
#   1 — real error (missing source structure, write failure)
#
# Standard tools only: bash, grep, sed, awk, find, sort. No external deps.

set -uo pipefail

ROOT="${1:-}"
if [ -z "$ROOT" ]; then
  ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
fi
cd "$ROOT" || { echo "[index-refresh] ERROR: cannot cd $ROOT" >&2; exit 1; }

log() { echo "[index-refresh] $*"; }
err() { echo "[index-refresh] ERROR: $*" >&2; }

STAMP=$(date '+%Y-%m-%d %H:%M')
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# ---------------------------------------------------------------
# Index 1 — docs/project/sprints/INDEX.md (all-sprints index)
# ---------------------------------------------------------------
build_sprints_index() {
  local out="docs/project/sprints/INDEX.md"
  local src_dir="docs/project/sprints"

  if [ ! -d "$src_dir" ]; then
    log "skip $out — $src_dir missing"
    return 0
  fi

  local rows=0
  {
    echo "# Sprints — Index"
    echo
    echo "<!-- AUTO-GENERATED by .claude/skills/index-refresh/scripts/refresh_indexes.sh. Do not hand-edit. -->"
    echo
    echo "| Sprint | Status | Opened | Closed |"
    echo "|---|---|---|---|"

    find "$src_dir" -maxdepth 1 -type f -name 'sprint-S*.md' \
      ! -name 'sprint-S*-index.md' ! -name 'INDEX.md' 2>/dev/null \
      | sort \
      | while read -r f; do
          local sprint status opened closed
          sprint=$(basename "$f" .md)
          status=$(grep -m1 -E '^> \*\*Status\*\*' "$f" 2>/dev/null \
                   | sed -E 's/^> \*\*Status\*\*[: ]*//; s/\*//g' \
                   | head -c 40)
          opened=$(grep -m1 -E '^> \*\*Opened\*\*' "$f" 2>/dev/null \
                   | sed -E 's/^> \*\*Opened\*\*[: ]*//; s/\*//g' \
                   | head -c 20)
          closed=$(grep -m1 -E '^> \*\*Closed\*\*' "$f" 2>/dev/null \
                   | sed -E 's/^> \*\*Closed\*\*[: ]*//; s/\*//g' \
                   | head -c 20)
          [ -z "$status" ] && status="—"
          [ -z "$opened" ] && opened="—"
          [ -z "$closed" ] && closed="—"
          echo "| [$sprint](./$(basename "$f")) | $status | $opened | $closed |"
        done
    echo
    echo "<!-- last-refresh: $STAMP -->"
  } > "$TMPDIR/sprints-index.md"

  rows=$(grep -c '^| \[sprint-' "$TMPDIR/sprints-index.md" || true)

  if ! cmp -s "$TMPDIR/sprints-index.md" "$out" 2>/dev/null; then
    mkdir -p "$(dirname "$out")"
    mv "$TMPDIR/sprints-index.md" "$out"
    log "rebuilt: $out ($rows rows)"
  else
    log "no change: $out ($rows rows)"
  fi
}

# ---------------------------------------------------------------
# Index 2 — docs/project/sprints/sprint-S<N>-index.md (per sprint)
# ---------------------------------------------------------------
build_sprint_task_index() {
  local sprint_file="$1"
  local sprint_name out rows
  sprint_name=$(basename "$sprint_file" .md)         # sprint-S04
  out="docs/project/sprints/${sprint_name}-index.md"

  {
    echo "# ${sprint_name} — Task Index"
    echo
    echo "<!-- AUTO-GENERATED by .claude/skills/index-refresh/scripts/refresh_indexes.sh. Do not hand-edit. -->"
    echo
    echo "| ID | Component | Status | Depends |"
    echo "|---|---|---|---|"

    # Task rows in a sprint file look like: | TG-S04.12 | ... | ... | ... |
    # We capture rows that start with `| <TASK-ID-LIKE> |`.
    grep -E '^\|\s*[A-Z][A-Z]+-S[0-9]+\.[0-9]+' "$sprint_file" 2>/dev/null \
      | awk -F'|' '{
          # Trim each field
          for (i = 1; i <= NF; i++) {
            gsub(/^ +| +$/, "", $i);
          }
          # Field 2 = ID, 3 = Component (or Title), 4 = Status, 5 = Depends (best effort)
          id = $2; comp = ($3 == "" ? "—" : $3);
          status = ($4 == "" ? "—" : $4);
          depends = ($5 == "" ? "—" : $5);
          # Limit fields to keep table narrow
          if (length(comp) > 40) comp = substr(comp, 1, 37) "...";
          if (length(status) > 20) status = substr(status, 1, 20);
          if (length(depends) > 20) depends = substr(depends, 1, 20);
          print "| " id " | " comp " | " status " | " depends " |";
        }'
    echo
    echo "<!-- last-refresh: $STAMP -->"
  } > "$TMPDIR/sprint-index.md"

  # Count only data rows (task IDs match prefix-S<N>.<NN>)
  rows=$(grep -cE '^\| [A-Z]+-S[0-9]+\.[0-9]+' "$TMPDIR/sprint-index.md" || true)

  if ! cmp -s "$TMPDIR/sprint-index.md" "$out" 2>/dev/null; then
    mkdir -p "$(dirname "$out")"
    mv "$TMPDIR/sprint-index.md" "$out"
    log "rebuilt: $out ($rows rows)"
  else
    log "no change: $out ($rows rows)"
  fi

  if [ "$rows" -eq 0 ]; then
    log "WARN $out has 0 rows — likely a parsing bug (sprint file shape changed?)"
  fi
}

# ---------------------------------------------------------------
# Index 3 — docs/project/backlog-index.md
# ---------------------------------------------------------------
build_backlog_index() {
  local src="docs/project/backlog.md"
  local out="docs/project/backlog-index.md"
  local rows

  if [ ! -f "$src" ]; then
    log "skip $out — $src missing"
    return 0
  fi

  {
    echo "# Backlog — Index"
    echo
    echo "<!-- AUTO-GENERATED by .claude/skills/index-refresh/scripts/refresh_indexes.sh. Do not hand-edit. -->"
    echo
    echo "| Sprint | Status | Pointer |"
    echo "|---|---|---|"

    # Sprint sections in backlog.md look like:
    #   ### Sprint S04 — <theme>
    # OR a status header like:
    #   ## 🚀 Active sprint
    awk '
      /^### Sprint S[0-9]+/ {
        # Extract the sprint identifier
        gsub(/^### /, "", $0);
        sprint = $0;
        # Default values; the next non-empty line may carry status hints
        next;
      }
      /^> \*\*Status\*\*/ && sprint != "" {
        status = $0;
        gsub(/^> \*\*Status\*\*[: ]*/, "", status);
        gsub(/\*/, "", status);
        # Print row
        # Pointer = anchor link within backlog.md
        anchor = tolower(sprint);
        gsub(/[^a-z0-9]+/, "-", anchor);
        sub(/^-/, "", anchor); sub(/-$/, "", anchor);
        print "| " sprint " | " status " | [↗](./backlog.md#" anchor ") |";
        sprint = "";
        next;
      }
      /^### Sprint S[0-9]+/ && sprint != "" {
        # New sprint heading and previous had no Status row -> emit it
        anchor = tolower(sprint);
        gsub(/[^a-z0-9]+/, "-", anchor);
        sub(/^-/, "", anchor); sub(/-$/, "", anchor);
        print "| " sprint " | — | [↗](./backlog.md#" anchor ") |";
      }
      END {
        if (sprint != "") {
          anchor = tolower(sprint);
          gsub(/[^a-z0-9]+/, "-", anchor);
          sub(/^-/, "", anchor); sub(/-$/, "", anchor);
          print "| " sprint " | — | [↗](./backlog.md#" anchor ") |";
        }
      }
    ' "$src"
    echo
    echo "<!-- last-refresh: $STAMP -->"
  } > "$TMPDIR/backlog-index.md"

  rows=$(grep -c '^| Sprint S' "$TMPDIR/backlog-index.md" || true)

  if ! cmp -s "$TMPDIR/backlog-index.md" "$out" 2>/dev/null; then
    mkdir -p "$(dirname "$out")"
    mv "$TMPDIR/backlog-index.md" "$out"
    log "rebuilt: $out ($rows rows)"
  else
    log "no change: $out ($rows rows)"
  fi

  if [ "$rows" -eq 0 ]; then
    log "WARN $out has 0 rows — backlog.md has no '### Sprint S<N>' sections?"
  fi
}

# ---------------------------------------------------------------
# Index 4 — docs/designs/sprint-S<N>/INDEX.md (per sprint design dir)
# ---------------------------------------------------------------
build_design_index() {
  local design_dir="$1"
  local sprint_name out rows
  sprint_name=$(basename "$design_dir")
  out="${design_dir}/INDEX.md"

  {
    echo "# ${sprint_name} — Design Docs Index"
    echo
    echo "<!-- AUTO-GENERATED by .claude/skills/index-refresh/scripts/refresh_indexes.sh. Do not hand-edit. -->"
    echo
    echo "| DXXX | Title | Status | Task |"
    echo "|---|---|---|---|"

    find "$design_dir" -maxdepth 1 -type f -name 'D*.md' \
      ! -name 'INDEX.md' 2>/dev/null \
      | sort \
      | while read -r f; do
          local fname dnum title status task
          fname=$(basename "$f" .md)                       # D012-add-tenant-invites
          dnum=$(echo "$fname" | grep -oE '^D[0-9]+' | head -1)
          # Title from first `# Design:` heading or filename
          title=$(grep -m1 -E '^# Design:?' "$f" 2>/dev/null \
                  | sed -E 's/^# Design:?[[:space:]]*//' \
                  | head -c 60)
          if [ -z "$title" ]; then
            title=$(echo "$fname" | sed -E "s/^D[0-9]+-//; s/-/ /g")
          fi
          status=$(grep -m1 -E '^> \*\*Status\*\*' "$f" 2>/dev/null \
                   | sed -E 's/^> \*\*Status\*\*[: ]*//; s/\*//g' \
                   | head -c 20)
          [ -z "$status" ] && status="—"
          task=$(grep -m1 -E '^> \*\*Task( Group)?\*\*' "$f" 2>/dev/null \
                 | sed -E 's/^> \*\*Task( Group)?\*\*[: ]*//; s/\*//g' \
                 | head -c 20)
          [ -z "$task" ] && task="—"
          echo "| $dnum | [$title](./$(basename "$f")) | $status | $task |"
        done
    echo
    echo "<!-- last-refresh: $STAMP -->"
  } > "$TMPDIR/design-index.md"

  rows=$(grep -c '^| D[0-9]' "$TMPDIR/design-index.md" || true)

  if ! cmp -s "$TMPDIR/design-index.md" "$out" 2>/dev/null; then
    mkdir -p "$(dirname "$out")"
    mv "$TMPDIR/design-index.md" "$out"
    log "rebuilt: $out ($rows rows)"
  else
    log "no change: $out ($rows rows)"
  fi

  if [ "$rows" -eq 0 ]; then
    log "WARN $out has 0 rows — no D<NNN>-*.md files in $design_dir?"
  fi
}

# ---------------------------------------------------------------
# Main
# ---------------------------------------------------------------

build_sprints_index

# Each active sprint file → its task index
find docs/project/sprints -maxdepth 1 -type f -name 'sprint-S*.md' \
  ! -name 'sprint-S*-index.md' ! -name 'INDEX.md' 2>/dev/null \
  | sort \
  | while read -r sf; do
      build_sprint_task_index "$sf"
    done

build_backlog_index

# Each sprint design dir → its design-doc index
find docs/designs -maxdepth 1 -type d -name 'sprint-S*' 2>/dev/null \
  | sort \
  | while read -r dd; do
      build_design_index "$dd"
    done

log "done"
exit 0
